name: Unit Tests

on:
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        version: ['lts/*', 'latest' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/pnpm-cached-setup
        with:
          version: ^7.30.0

      - name: Run Type Checks
        run: pnpm type-check

      - name: Run Tests
        run: pnpm test:coverage